spring.application.name: bus-ticketing

whatsapp:
  encryption:
    private-key-path: keys/private_key.pem
    public-key-path: keys/public_key.pem

  app:
    secret: ${ZAP_TEST_APP_SECRET}
  api:
    base-url: https://graph.facebook.com
    version: v22.0
    # This value is loaded from an environment variable set in the OS (.zshrc, Docker env, etc.)
    access-token: ${WHATSAPP_BUSINESS_API_TOKEN}
    whatsapp-business-account-id: 553980767801243
    phone-number: 15551944707
    phone-number-id: 571710919355097
server:
  port: 3000

# Point to the bus_10_seats.png under classpath:static
seating:
  base-images:
    - classpath:static/bus_10_seats.png

bus:
  layout:
    font:
      seat-label-size: 14
      driver-label-size: 16
      toilet-label-size: 14
      legend-label-size: 14
    # ───────── Numeric parameters ─────────
    rows:              5      # now 5 “rows” including driver row
    cols-left:         2      # how many “left-block” cells per row
    cols-right:        1      # how many “right-block” cells per row
    seat-size:         60     # each seat (and toilet/empty) is 60×60 px
    seat-gap:          10     # 10px gap between seats/toilet blocks
    aisle-width:       40     # width of the aisle in pixels
    padding:           20     # 20px padding around all edges
    driver-area-height: 80    # height of the DRIVER / ENTRANCE row boxes
    label-height:       40    # vertical space above driver boxes for “Driver”/“Entrance” text

    # ───────── layoutMap: exactly one list-of-lists of length = rows × (cols-left + cols-right) ─────────
    # Each inner list must have length = cols-left + cols-right = 3 in this example.
    # Valid values are the names of CellType: DRIVER, ENTRANCE, SEAT, TOILET, EMPTY
    layout-map:
      - ["DRIVER",  "EMPTY",   "ENTRANCE"]  # Row 0: driver box, a blank, and entrance box
      - ["SEAT",    "SEAT",    "SEAT"    ]  # Row 1: three passenger seats (A1, B1, C1)
      - ["SEAT",    "SEAT",    "TOILET"  ]  # Row 2: seats A2, B2, and a toilet at C2
      - ["SEAT",    "SEAT",    "EMPTY"   ]  # Row 3: seats A3, B3, and an empty placeholder at C3
      - ["SEAT",    "SEAT",    "EMPTY"   ]  # Row 4: seats A4, B4, and an empty placeholder at C4
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=24h

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.tazifor: debug
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: warn